theme: jekyll-theme-cayman
title: 'Selina Hofstetter'
tagline: Site Tagline
description: 'PhD Candidate, London School of Economics & Political Science'
show_downloads: false

# Social media links
email : S.Hofstetter1@lse.ac.uk
github : Sehoof
