theme: jekyll-theme-cayman
title: 'Selina Hofstetter'
description: 'PhD Candidate in Political Science, London School of Economics & Political Science'
show_downloads: true
github:
  zip_url: http://selinahofstetter.ch/download.zip
  another_url: http://selinahofstetter.ch/CV
