theme: jekyll-theme-cayman
title: 'Selina Hofstetter'
description: 'Postdoctoral Fellow in Political Science <br/>
@ Stanford University'
show_downloads: false
@import: url("https://raw.githubusercontent.com/sehoof/sehoof.github.io/master/images/foto_SH.jpg");
