theme: jekyll-theme-cayman
title: 'Selina Hofstetter'
description: 'Ph.D. candidate in Political Science <br/>
London School of Economics & Political Science <br/>
Research interests: Democratisation, Women's Vote & Historical Political Economy'
show_downloads: false
