theme: jekyll-theme-cayman
title: 'Selina Hofstetter'
description: 'Postdoctoral Fellow in Political Science <br/>
@ Stanford University'
logo: https://raw.githubusercontent.com/sehoof/sehoof.github.io/master/images/foto_SH.jpg
show_downloads: false
